version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:80'
    volumes:
      - ./frontend:/app
